export const DATA_SPREADSHEET = "1_meMQpT8_WqRk_snCsJoaC1jg3diRQni7gXEjMTl6xA";
export const MONEY_SPREADSHEET = "1W302muFHMUcXIMCJtO9Scd0LnM7WJ_2XHhuAPCT2Y-E";

export const CHAT_GROUP_LIST_RANGE_FIRST_COLUMN_DELTA = 4;